sudo: required
dist: trusty
git:
  depth: 1

branches:
  only:
    - 'master'

language: node_js
node_js:
  - '6'
  - '7'
  - stable

cache:
  directories:
  - $HOME/.npm

addons:
  chrome: stable

matrix:
  fast_finish: true

env:
  matrix:
    - CASE=cordova/bootstrap
    - CASE=cordova/bootstrap-authentication
    - CASE=cordova/ionic
    - CASE=cordova/ionic-authentication
    - CASE=cordova/material
    - CASE=cordova/material-authentication
    - CASE=web/bootstrap
    - CASE=web/bootstrap-authentication
    - CASE=web/ionic
    - CASE=web/ionic-authentication
    - CASE=web/material
    - CASE=web/material-authentication
    - CASE=web+cordova/bootstrap-authentication
    - CASE=web+cordova/ionic-authentication
    - CASE=web+cordova/material-authentication
      NGX_PACKAGE_MANAGER=yarn

install:
  - npm install -g yo
  - npm install
  - npm link

before_script:
  - export DBUS_SESSION_BUS_ADDRESS=/dev/null
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm test $CASE
