version: 2

general:
  branches:
    only:
      #- master
      - feature/circleci

jobs:
  build:
    docker:
      - image: circleci/node:8
    working_directory: ~/generator-ngx-rocket
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - npm-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - npm-dependencies-

      - run:
          name: install-yarn
          command: npm install -g yarn@latest

      - run:
          name: npm-install
          command: npm install

      - run:
          name: npm-link
          command: npm link

      - save_cache:
          paths:
            - node_modules
          key: npm-dependencies-{{ checksum "package.json" }}

      - run: npm test app/cordova/bootstrap

