version: 2

general:
  branches:
    only:
      #- master
      - feature/circleci

jobs:
  build:
    docker:
      - image: circleci/node:8
        env:
          - DISPLAY=:99
          - DBUS_SESSION_BUS_ADDRESS=/dev/null
    working_directory: ~/generator-ngx-rocket
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - npm-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - npm-dependencies-

      - run: sudo sh -e /etc/init.d/xvfb start

      - run:
          name: Install yarn
          command: sudo npm install -g yarn@latest

      - run:
          name: npm install
          command: npm install

      - run:
          name: npm link
          command: sudo npm link

      - save_cache:
          paths:
            - node_modules
          key: npm-dependencies-{{ checksum "package.json" }}

      - run:
          name: Run tests
          command: npm test app/cordova/bootstrap

